apiVersion: apps/v1
kind: Deployment
metadata:
  name: ar-mongo-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ar-mongo
  template:
    metadata:
      labels:
        app: ar-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.4.2
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ar-mongo-service
spec:
  selector:
    app: ar-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
