# YAML file with two deployments and two services

# Deployment for Service 1 (creates a pod for service 1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: myservice1-image
          ports:
            - containerPort: 8080

---

# Deployment for Service 2 (creates a pod for service 2)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: myservice2-image
          ports:
            - containerPort: 8081

---

# Service for Service 1
apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---

# Service for Service 2
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
