# testing_service.yaml
#image: helloardanish/testing-build:latest

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-service
  template:
    metadata:
      labels:
        app: testing-service
    spec:
      containers:
        - name: testing-service
          image: helloardanish/testing-build:latest
          ports:
            - containerPort: 8080





# kubectl apply -f testing_service.yaml
#apiVersion: v1
#kind: Service
#metadata:
#  name: testing-service
#spec:
#  selector:
#    app: testing-service
#  ports:
#    - protocol: TCP
#      port: 80           # Exposes this port on the service
#      targetPort: 8080    # Maps to the container port
#      nodePort: 30080     # The port you can access on your local machine
#  type: NodePort



---


apiVersion: v1
kind: Service
metadata:
  name: testing-service
spec:
  selector:
    app: testing-service
  ports:
    - protocol: TCP
      port: 80         # Exposes this port on the service
      targetPort: 8080    # Maps to the container port
  #      nodePort: 30080     # The port you can access on your local machine
  type: NodePort


# > minikube ip
#  192.168.58.2
#  http://192.168.58.2:30080/test
#
# > minikube service testing-service


